# overlays/version-pinning.nix
# Centralized version pinning to prevent duplicates
# Generated by: fix-version-duplicates.sh

final: prev: {
  # =========================================================================
  # PYTHON VERSION STANDARDIZATION (CRITICAL)
  # =========================================================================
  # Force single Python version system-wide
  # Found issue: 19 different python3 versions in system

  python3 = prev.python312; # Use Python 3.12 as standard
  python = prev.python312; # Alias python to python3.12

  # Explicitly remove other Python versions from default packages
  # This prevents inadvertent installation of python3.11, 3.13, etc.

  # =========================================================================
  # GCC/COMPILER STANDARDIZATION
  # =========================================================================
  # Force single GCC version
  # Found issue: 13 different gcc versions

  gcc = prev.gcc13; # Use GCC 13 as standard
  stdenv = prev.stdenvAdapters.withCFlags [ "-march=native" "-mtune=native" ] prev.stdenv;

  # =========================================================================
  # CUDA VERSION STANDARDIZATION (if using CUDA)
  # =========================================================================
  # Force single CUDA version
  # Prevents mixing CUDA 11.x and 12.x

  cudaPackages = prev.cudaPackages_12_8; # CUDA 12.8 as standard

  # =========================================================================
  # ELECTRON VERSION STANDARDIZATION
  # =========================================================================
  # Force single Electron version for all Electron apps
  # Prevents multiple electron versions

  electron = prev.electron_38; # Electron 38 as standard

  # Note: Chromium-based apps (brave, vscodium) should NOT be overridden
  # They should use the standard nixpkgs versions
  # The chromium-log-suppression overlay should be REMOVED

  # =========================================================================
  # FFMPEG STANDARDIZATION
  # =========================================================================
  # Force single ffmpeg version
  # Found issue: 7 different ffmpeg versions

  ffmpeg = prev.ffmpeg-full; # Use full-featured ffmpeg consistently

  # =========================================================================
  # SYSTEM LIBRARY STANDARDIZATION
  # =========================================================================

  # Use consistent libxml2 version
  libxml2 = prev.libxml2;

  # Use consistent curl version
  curl = prev.curl;

  # Use consistent sqlite version
  sqlite = prev.sqlite;
}
