# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-faeac278-02a6-47c3-bf09-7800a44afdbb";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-faeac278-02a6-47c3-bf09-7800a44afdbb".device =
    "/dev/disk/by-uuid/faeac278-02a6-47c3-bf09-7800a44afdbb";

  # LUKS swap partition (available but unused — zram preferred over disk swap)
  # boot.initrd.luks.devices."luks-1cee1bf1-a159-4d91-b531-65437ce5c6b5".device =
  #   "/dev/disk/by-uuid/1cee1bf1-a159-4d91-b531-65437ce5c6b5";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CCB7-13F0";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # SWAP em disco desabilitado - usando apenas zram (7.7GB) + swapfile (4GB emergency)
  # Benefícios: Menor latência, menos I/O, maior durabilidade do SSD
  # swapDevices = [{ device = "/dev/mapper/luks-1cee1bf1-a159-4d91-b531-65437ce5c6b5"; }];
  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
