# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  boot.extraModulePackages = [ ];

  # Root filesystem via LUKS (correct UUIDs from nixos-generate-config)
  fileSystems."/" = {
    device = "/dev/mapper/luks-8eb42765-659f-4565-ad7e-6d56984d5018";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8eb42765-659f-4565-ad7e-6d56984d5018".device =
    "/dev/disk/by-uuid/8eb42765-659f-4565-ad7e-6d56984d5018";

  # LUKS swap partition (available but unused — zram preferred over disk swap)
  # boot.initrd.luks.devices."luks-3e48d8d8-0371-46f3-a981-43463a388a0d".device =
  #   "/dev/disk/by-uuid/3e48d8d8-0371-46f3-a981-43463a388a0d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4D17-E804";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # SWAP em disco desabilitado - usando apenas zram (7.7GB) + swapfile (4GB emergency)
  # Benefícios: Menor latência, menos I/O, maior durabilidade do SSD
  # swapDevices = [{ device = "/dev/mapper/luks-3e48d8d8-0371-46f3-a981-43463a388a0d"; }];
  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
