#!/usr/bin/env bash
# fix-version-duplicates.sh
# Automated fix for package version duplicates

set -euo pipefail

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${CYAN}${BOLD}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║      🔧 NixOS Version Duplicate Fixer 🔧                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

# ===========================================================================
# PHASE 1: Analyze current flake.nix for version pinning issues
# ===========================================================================

echo -e "${YELLOW}[1/4] Analyzing flake.nix for nixpkgs pinning...${NC}"

FLAKE_FILE="/etc/nixos/flake.nix"

if [ ! -f "$FLAKE_FILE" ]; then
    echo -e "${RED}ERROR: $FLAKE_FILE not found${NC}"
    exit 1
fi

# Check if inputs are following nixpkgs
UNPINNED_INPUTS=$(grep -E '^\s+\w+\.url = "github:' "$FLAKE_FILE" | \
    grep -v nixpkgs | \
    sed 's/\.url.*//' | \
    sed 's/^\s*//' || true)

if [ -n "$UNPINNED_INPUTS" ]; then
    echo -e "${YELLOW}  ⚠ Found unpinned inputs:${NC}"
    echo "$UNPINNED_INPUTS" | sed 's/^/    /'
else
    echo -e "${GREEN}  ✓ All inputs appear to follow nixpkgs${NC}"
fi

# ===========================================================================
# PHASE 2: Create version pinning overlay
# ===========================================================================

echo -e "${YELLOW}[2/4] Creating version pinning overlay...${NC}"

OVERLAY_DIR="/etc/nixos/overlays"
OVERLAY_FILE="$OVERLAY_DIR/version-pinning.nix"

mkdir -p "$OVERLAY_DIR"

cat > "$OVERLAY_FILE" << 'NIXEOF'
# overlays/version-pinning.nix
# Centralized version pinning to prevent duplicates
# Generated by: fix-version-duplicates.sh

final: prev: {
  # =========================================================================
  # PYTHON VERSION STANDARDIZATION (CRITICAL)
  # =========================================================================
  # Force single Python version system-wide
  # Found issue: 19 different python3 versions in system

  python3 = prev.python312;  # Use Python 3.12 as standard
  python = prev.python312;   # Alias python to python3.12

  # Explicitly remove other Python versions from default packages
  # This prevents inadvertent installation of python3.11, 3.13, etc.

  # =========================================================================
  # GCC/COMPILER STANDARDIZATION
  # =========================================================================
  # Force single GCC version
  # Found issue: 13 different gcc versions

  gcc = prev.gcc13;   # Use GCC 13 as standard
  stdenv = prev.stdenvAdapters.withCFlags
    [ "-march=native" "-mtune=native" ]
    prev.stdenv;

  # =========================================================================
  # CUDA VERSION STANDARDIZATION (if using CUDA)
  # =========================================================================
  # Force single CUDA version
  # Prevents mixing CUDA 11.x and 12.x

  cudaPackages = prev.cudaPackages_12_8;  # CUDA 12.8 as standard

  # =========================================================================
  # ELECTRON VERSION STANDARDIZATION
  # =========================================================================
  # Force single Electron version for all Electron apps
  # Prevents multiple electron versions

  electron = prev.electron_38;  # Electron 38 as standard

  # Note: Chromium-based apps (brave, vscodium) should NOT be overridden
  # They should use the standard nixpkgs versions
  # The chromium-log-suppression overlay should be REMOVED

  # =========================================================================
  # FFMPEG STANDARDIZATION
  # =========================================================================
  # Force single ffmpeg version
  # Found issue: 7 different ffmpeg versions

  ffmpeg = prev.ffmpeg-full;  # Use full-featured ffmpeg consistently

  # =========================================================================
  # SYSTEM LIBRARY STANDARDIZATION
  # =========================================================================

  # Use consistent libxml2 version
  libxml2 = prev.libxml2;

  # Use consistent curl version
  curl = prev.curl;

  # Use consistent sqlite version
  sqlite = prev.sqlite;
}
NIXEOF

echo -e "${GREEN}  ✓ Created $OVERLAY_FILE${NC}"

# ===========================================================================
# PHASE 3: Update flake.nix to use overlay
# ===========================================================================

echo -e "${YELLOW}[3/4] Checking if overlay is imported in configuration...${NC}"

# Check if overlays directory is imported
if grep -q "nixpkgs.overlays.*overlays/version-pinning" "$FLAKE_FILE" || \
   grep -q "import.*overlays/version-pinning" /etc/nixos/hosts/*/configuration.nix 2>/dev/null || \
   grep -q "import.*overlays" /etc/nixos/hosts/*/configuration.nix 2>/dev/null; then
    echo -e "${GREEN}  ✓ Overlay import found${NC}"
else
    echo -e "${YELLOW}  ⚠ Overlay not imported yet${NC}"
    echo ""
    echo -e "${CYAN}Add this to your configuration.nix:${NC}"
    echo ""
    cat << 'NIXEXAMPLE'
  nixpkgs.overlays = [
    (import ./overlays/version-pinning.nix)
  ];
NIXEXAMPLE
    echo ""
fi

# ===========================================================================
# PHASE 4: Create follow-up action plan
# ===========================================================================

echo -e "${YELLOW}[4/4] Creating action plan...${NC}"

cat > /tmp/VERSION-FIX-PLAN.md << 'EOF'
# Version Duplicate Fix - Action Plan

## Files Created

1. `/etc/nixos/overlays/version-pinning.nix` - Centralized version pinning overlay

## Manual Steps Required

### Step 1: Import overlay (CRITICAL)

Add to `/etc/nixos/hosts/kernelcore/configuration.nix`:

```nix
nixpkgs.overlays = [
  (import ../../overlays/version-pinning.nix)
];
```

### Step 2: Update flake.nix inputs to follow nixpkgs

Ensure ALL inputs follow the same nixpkgs:

```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Make ALL inputs follow nixpkgs
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    hyprland.url = "git+https://github.com/hyprwm/Hyprland";
    hyprland.inputs.nixpkgs.follows = "nixpkgs";

    # ... repeat for ALL inputs
  };
}
```

### Step 3: Remove conflicting overlays

These overlays create duplicate derivations:

- `/etc/nixos/modules/applications/chromium-log-suppression.nix` (lines 106-138)
- `/etc/nixos/modules/applications/electron-tuning.nix` (lines 61-91)

**Action:** Delete the `nixpkgs.overlays` blocks from these files

### Step 4: Rebuild and verify

```bash
# Update flake.lock
nix flake update --commit-lock-file

# Check for errors
nix flake check

# Rebuild
sudo nixos-rebuild switch

# Verify duplicates reduced
/etc/nixos/scripts/analyze-package-versions.sh

# Compare before/after
diff /tmp/nix-version-analysis/duplicate-counts.txt \
     /tmp/nix-version-analysis-new/duplicate-counts.txt
```

## Expected Results

**Before:**
- Python versions: 19
- GCC versions: 13
- Total duplicates: ~472 packages

**After:**
- Python versions: 1-2 (python312 + possibly one legacy)
- GCC versions: 1-2 (gcc13 + stdenv)
- Total duplicates: ~50-100 packages (-80%)

**Disk savings:** ~10-15 GB
**Rebuild time improvement:** Additional 10-20% faster (on top of cache fixes)

## Verification

```bash
# Count Python versions after fix
nix-store --query --requisites /run/current-system | \
  grep -E '/python3\.[0-9]+-' | \
  sed 's/-[0-9].*//' | \
  sort -u | \
  wc -l

# Should output: 1 or 2 (down from 19)

# Count GCC versions
nix-store --query --requisites /run/current-system | \
  grep -E '/gcc-[0-9]' | \
  sed 's/-[0-9].*//' | \
  sort -u | \
  wc -l

# Should output: 1-2 (down from 13)
```

## Rollback if needed

```bash
sudo nixos-rebuild switch --rollback
```

---

**Generated by:** fix-version-duplicates.sh
**Next:** Follow steps 1-4 above
EOF

cat /tmp/VERSION-FIX-PLAN.md

echo ""
echo -e "${GREEN}${BOLD}✓ Version duplicate fix prepared!${NC}"
echo ""
echo -e "${CYAN}Files created:${NC}"
echo "  1. /etc/nixos/overlays/version-pinning.nix"
echo "  2. /tmp/VERSION-FIX-PLAN.md"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. cat /tmp/VERSION-FIX-PLAN.md"
echo "  2. Follow manual steps 1-4"
echo "  3. Rebuild and verify"
echo ""
